PORTS_DIR=/var/cache/alps/ports/
SOURCES_DIR=/var/cache/alps/sources/
PACKAGES_DIR=/var/cache/alps/packages/
STAGING_DIR=/var/cache/alps/staging/
INSTALLED_DIR=/var/lib/alps/installed/
REPO_VERSION=3.0
